config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#indexbf"
  get 'index', to:"home#index"
  post 'index', to:"home#new"
  get 'categories1',to:"home#categories1"
  get "signup", to: "users#new"
  get "login", to: "sessions#login"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  get "suggestions", to:"home#suggestions"

resources :users,except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category <ApplicationRecord
    belongs_to :interest
    has_many :home
    has_many :user, through: :home
end

app/models/home.rb
class Home<ApplicationRecord
    belongs_to :interest
    belongs_to :category
    belongs_to :user
    
    def self.category_by_users(homes,current_user)
        similarity_percent = {}
        similar_category = {}
        usercatarray = homes.pluck(:user_id,:category_id)
        user_category_hash = usercatarray.group_by(&:first).transform_values { |pairs| pairs.map(&:last) }
        currentid = current_user.id
        current_user_category = user_category_hash[currentid]
        rest_user_category_hash = user_category_hash.except(currentid)
        rest_user_category_hash.each do |user_id, category_list|
           Rails.logger.info ("inside loop")   
           Rails.logger.info ("#{current_user_category} helo" + " #{category_list} ") 
           similarity_percentage = category_similarity_percentage(current_user_category, category_list)  
           similarity_percent[user_id] = similarity_percentage  
           similar_category[user_id] = current_user_category & category_list
        end
        [similarity_percent,similar_category]
        
    end
    def self.category_similarity_percentage(arr1, arr2)  
        smaller_size = [arr1.length, arr2.length].min  
        intersection_size = (arr1 & arr2).length
        similarity_percentage = intersection_size.to_f / smaller_size * 100  
        similarity_percentage.round(2)
    end

    def self.get_categories(similar_category_hash,category)
        selectedcategory = {}
        similar_category_hash.each do |userid,categories_id|
            selectedcategory[userid] = categories_id.map{|id| category.find {|c| c[:id] == id}[:name]}
        end
        selectedcategory
  
    end

end

app/models/interest.rb
class Interest <ApplicationRecord
    has_many :category
    has_many :home, through: :category
    has_many :user, through: :home
end

app/models/user.rb
class User <ApplicationRecord
    has_secure_password
    has_many :home, dependent: :destroy
    has_many :category, through: :home
    has_many :interest, through: :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?  
  def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
 
  def logged_in?
    !!current_user
  end
 
  def require_user
   if !logged_in?
     flash[:alert] = "You must be logged in to perform that action."
     redirect_to login_path
   end
  end
end

app/controllers/home_controller.rb
class HomeController<ApplicationController
  def new   
      @home=Home.new 
      @home = Home.new(home_params)
      if @home.save
        redirect_to root_path
      else
        redirect_to root_path
      end 
      
  end

  def index
    @interest = Interest.all
    @cat=Category.all
    @homes=Home.all
    @category=Category.all.pluck(:id,:name).to_h  
  end
   
  def suggestions
    @homes=Home.all
    @otherusers=User.all
    @category=Category.all 
    @similarity_percent,@similar_category_hash = Home.category_by_users(@homes,current_user)
    @similar_category_record = Home.get_categories(@similar_category_hash,@category)
  end

   private 
    def home_params
      params.permit(:interest_id, :user_id, :category_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController<ApplicationController
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
          session[:user_id] = user.id
          flash[:notice] = "Logged in successfully."
          redirect_to index_path
        else
          flash.now[:alert] = "There was something wrong with your login details."
          render 'login'
        end
      end
       
      def destroy
        session[:user_id] = nil
        flash[:notice] = "You have been logged out."
        redirect_to root_path
      end
end
  

app/controllers/users_controller.rb
class UsersController<ApplicationController
    def new
        @user=User.new       
    end
    def create
        @user = User.new(user_params)
        if @user.save
        #   flash[:notice] = "User created."
          redirect_to login_path
        else
          render 'new'
        end
      end
      
      def edit
        if !logged_in?
          #redirect to login page
        else
          #do cool stuff
      end
    end

     private 
      def user_params
        params.require(:user).permit(:name, :email, :password)
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_headeraf.html.erb
<html>
<style>
table, td, th {
  border: 1px solid;
}

table {
  width: 50%;
  border-collapse: collapse;
}
.capi{
  text-transform: uppercase;
}
button {
    width:30%;
    margin-bottom: 15px;
    color: #fff;
    font-size: 20px;
    font-weight: 600;
    border-radius: 5px;
    border: none;
    padding: 13px 0;
    cursor: pointer;
    background: green;
    margin-left:2vw;
}
button:hover {
    background: #1877f2;
}
</style>
<link rel="stylesheet" href="signup.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<a class="navbar-brand" href="#">
<%= link_to root_path do %>
<%= image_tag "dostlogo.jpg",class:"d-inline-block align-top", style:'height:60px;width:120px;'%>
<%end%>
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
    <%=link_to 'Suggestions',suggestions_path,class:"nav-link" %>
    <%=link_to 'Profile',index_path,class:"nav-link" %>
    <%=link_to 'Logout', logout_path,class:"nav-link" %>
    </form>
  </div>
</nav>

app/views/home/_headerbf.html.erb
<html>
<body>
<style>
.ml11 {
  font-weight: 600;
  font-size: 2.5em;
}

.ml11 .text-wrapper {
  position: relative;
  display: inline-block;
  padding-top: 0.1em;
  padding-right: 0.05em;
  padding-bottom: 0.15em;
}

.ml11 .line {
  opacity: 0;
  position: absolute;
  left: 0;
  height: 100%;
  width: 3px;
  background-color:#000000;;
  transform-origin: 0 50%;
}

.ml11 .line1 { 
  top: 0; 
  left: 0;
  color:#000000;
}

.ml11 .letter {
  display: inline-block;
  line-height: 1em;
  color:#000000;
}
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<a class="navbar-brand" href="#">
<%= link_to root_path do %>
<%= image_tag "dostlogo.jpg",class:"d-inline-block align-top", style:'height:60px;width:120px;'%>
<%end%>
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
    <%=link_to 'Sign Up', signup_path,class:"nav-link" %>
    <%=link_to 'Login', login_path,class:"nav-link" %>
    </form>
  </div>
</nav>

app/views/home/categories1.html.erb
<html>
<head>
<style>
.button {
  background-color: #4CAF50; /* Green */
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 6px 4px;
  cursor: pointer;
  -webkit-transition-duration: 0.4s; /* Safari */
  transition-duration: 0.4s;
  margin-left:60vw;
  margin-top:-30vw;
}
.button2:hover {
  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}
</style>
</head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
<br>
<center><h1><% home=Home.where(interest_id:params[:id]).take%><%=home.interest.name%></h1>
</center>
<% Home.where(interest_id:params[:id]).find_each do |home| %>
<div class="card-deck" style="margin-left:5vw;margin-right:5vw;margin-top:2vw;">
  <div class="card">
    <div class="card-body">
      <h5>NAME OF USER:</h5>
      <h5 class="card-title" style="text-transform: uppercase;"><%=home.user.name%></h5>
      <br>
      <h5>FIELD OF INTEREST:</h5>
      <p class="card-text"><%=home.category.name%></p>
      <button class="button button2">Contact</button>
    </div>
  </div>
  </div>
</div>
<%end%>
</body>
</html> 

app/views/home/index.html.erb
<html>
<style>
table, td, th {
  border: 1px solid;
}

table {
  width: 50%;
  border-collapse: collapse;
}
.capi{
  text-transform: uppercase;
}
button {
    width:30%;
    margin-bottom: 15px;
    color: #fff;
    font-size: 20px;
    font-weight: 600;
    border-radius: 5px;
    border: none;
    padding: 13px 0;
    cursor: pointer;
    background: green;
    margin-left:2vw;
}
button:hover {
    background: #1877f2;
}
</style>
<link rel="stylesheet" href="signup.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
<br>
<br>
<div style="margin-left:15vw;margin-right:15vw;">
<center>
<h1 class="capi">Hello, <%=current_user.name%>! FILL YOUR INTEREST </h1>
<br>
<div style="border:black; border-width:2px; border-style:solid;">
<%= form_with(model: @home, local: true) do |f| %>
  <div class="form-group">
  <label for="desc" style="font-size:1.5vw">Choose Your Category Of Interest</label><br>
  <%= f.select :interest_id, Interest.all.map { |t| [t.name,t.id]}, {} %>
    </div>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="form-group">
  <%= f.select :category_id, Category.all.map { |t| [t.name,t.id]}, {} %>
  </div>
  <div class="form-group">
  <button onclick= "<%=f.submit %>Save</button>
  </div>
  <% end %>
  </div>
  <br>
<h2>Your Interests</h2>
<table>   
       <tr>   
        <th>Interest</th>  
        <th>Description</th>
      </tr>   
      <% Home.where(user_id:current_user.id).find_each do |home| %>
          <tr>   
            <td><%= home.interest.name %></td>   
            <td><%= home.category.name%></td>  
            </tr>
            <% end %>
</table> 
</div>
</center>

app/views/home/indexbf.html.erb
<html>
<body>
<style>
.ml11 {
  font-weight: 600;
  font-size: 2.5em;
}

.ml11 .text-wrapper {
  position: relative;
  display: inline-block;
  padding-top: 0.1em;
  padding-right: 0.05em;
  padding-bottom: 0.15em;
}

.ml11 .line {
  opacity: 0;
  position: absolute;
  left: 0;
  height: 100%;
  width: 3px;
  background-color:#000000;;
  transform-origin: 0 50%;
}

.ml11 .line1 { 
  top: 0; 
  left: 0;
  color:#000000;
}

.ml11 .letter {
  display: inline-block;
  line-height: 1em;
  color:#000000;
}
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
<br>
<center>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
    <%= image_tag "f1.jpg",class:"d-block w-50" %>
    </div>
    <div class="carousel-item">
    <%= image_tag "f2.jpg",class:"d-block w-50" %>
    </div>
    <div class="carousel-item">
    <%= image_tag "f3.jpg",class:"d-block w-50" %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-target="#carouselExampleIndicators" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-target="#carouselExampleIndicators" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </button>
</div>
<br>
<h1 class="ml11">
<span class="text-wrapper">
  <span class="line line1"></span>
  <span class="letters">Find People Of Similar Interests Under One Roof</span>
</span>
</h1>
<br>
<div class="row row-cols-1 row-cols-md-2" style="margin-left:2vw;margin-right:2vw;">
  <div class="col mb-4">
  <%= link_to categories1_path(id:1) do %>
    <div class="card">
    <center>
    <%= image_tag "sports.jpg",class:"card-img-top",style:'height:15vw;width:20vw;'%></center>
      <div class="card-body" ,style="text-decoration:none;">
        <h5 class="card-title" style="text-decoration:none;">Sports</h5>
        <p class="card-text" ,style="text-decoration:none;">People having the similar interests in sports can connect with each other.</p>
      </div>
      <% end %>
    </div>
  </div>
  <div class="col mb-4">
  <%= link_to categories1_path(id:2) do %>
    <div class="card">
    <center>
    <%= image_tag "arts.jpg",class:"card-img-top",style:'height:15vw;width:20vw;'%></center>
      <div class="card-body">
        <h5 class="card-title">Arts & Crafts</h5>
        <p class="card-text">People having the similar interests in arts&crafts can connect with each other.</p>
      </div>
      <% end %>
    </div>
  </div>
  <div class="col mb-4">
  <%= link_to categories1_path(id:3) do %>
    <div class="card">
    <center>
    <%= image_tag "tech.jpg",class:"card-img-top",style:'height:15vw;width:20vw;'%></center>
      <div class="card-body">
        <h5 class="card-title">Technology</h5>
        <p class="card-text">People having the similar interests in technology can connect with each other.</p>
      </div>
      <% end %>
    </div>
  </div>
  <div class="col mb-4">
  <%= link_to categories1_path(id:4) do %>
    <div class="card">
    <center>
    <%= image_tag "automobiles.jpg",class:"card-img-top",style:'height:15vw;width:20vw;'%></center>
      <div class="card-body">
        <h5 class="card-title">Automobiles</h5>
        <p class="card-text">People having the similar interests in automobiles can connect with each other.</p>
      </div>
    </div>
    <% end %>
  </div>
</div>

</center>
<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
<script>// Wrap every letter in a span
var textWrapper = document.querySelector('.ml11 .letters');
textWrapper.innerHTML = textWrapper.textContent.replace(/([^\x00-\x80]|\w)/g, "<span class='letter'>$&</span>");

anime.timeline({loop: true})
  .add({
    targets: '.ml11 .line',
    scaleY: [0,1],
    opacity: [0.5,1],
    easing: "easeOutExpo",
    duration: 700
  })
  .add({
    targets: '.ml11 .line',
    translateX: [0, document.querySelector('.ml11 .letters').getBoundingClientRect().width + 10],
    easing: "easeOutExpo",
    duration: 700,
    delay: 100
  }).add({
    targets: '.ml11 .letter',
    opacity: [0,1],
    easing: "easeOutExpo",
    duration: 600,
    offset: '-=775',
    delay: (el, i) => 34 * (i+1)
  }).add({
    targets: '.ml11',
    opacity: 0,
    duration: 1000,
    easing: "easeOutExpo",
    delay: 1000
  });
  </script>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html>

app/views/home/suggestions.html.erb
<html>
<head>
<style>
.capi{
  text-transform: uppercase;
}
.button {
  background-color: #4CAF50; /* Green */
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 6px 4px;
  cursor: pointer;
  -webkit-transition-duration: 0.4s; /* Safari */
  transition-duration: 0.4s;
  width:150px;
}
.button2:hover {
  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}
</style>
</head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
<body>
<center>
<h1>Suggestion Of Friends With Similar Interest</h1>
<br>
<table>
  <tr>
    <th>&nbsp&nbsp&nbsp&nbsp User Name</th>
    <th>&nbsp&nbsp&nbsp&nbsp Match Percentage</th>
    <th>&nbsp&nbsp&nbsp&nbsp Common Interests</th>
    <th>&nbsp&nbsp&nbsp&nbsp Connect</th>
  </tr>
  <% @otherusers.each do |u| %>
    <tr>
    <% if(@similarity_percent[u.id] != 0.0 && @similar_category_record[u.id]!= nil )%>
    <td class="capi">&nbsp&nbsp&nbsp&nbsp<%=u.name%></td>
    <td>&nbsp&nbsp&nbsp&nbsp<%=@similarity_percent[u.id]%></td>
    <td>&nbsp&nbsp&nbsp&nbsp<%=@similar_category_record[u.id]%></td>
    <td>&nbsp&nbsp&nbsp&nbsp<button class="button button2">Contact</button></td>
    <%else%>
    <% end%>
    </tr>
  <% end %>
</table>
<br>
<br>
<h1>Suggestion Of Friends With Other Interest</h1>
<br>
<table>
  <tr>
    <th>&nbsp&nbsp&nbsp&nbsp User Name</th>
    <th>&nbsp&nbsp&nbsp&nbsp Interests</th>
    <th>&nbsp&nbsp&nbsp&nbsp Connect</th>
  </tr>
  <% @otherusers.each do |u| %>
    <% home=Home.where(user_id:u.id).take%>
    <td class="capi">&nbsp&nbsp&nbsp&nbsp<%=u.name%></td>
    <td>&nbsp&nbsp&nbsp&nbsp<%=home.category.name%></td>
    <td>&nbsp&nbsp&nbsp&nbsp<button class="button button2">Contact</button></td>
    </tr>
  <% end %>
</table>
</center>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friendsmain</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if logged_in? %>
     <%=render 'home/headeraf'%>
  <% else %>
    <%=render 'home/headerbf'%>
  <%end%>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<link rel="stylesheet" href="signup.css">
<div class="box" style="margin-top:-5vw;">
  <div class="title-box">
  <%= link_to root_path do %>
  <%= image_tag "dostlogo.jpg",class:"title-box-img" %>
  <%end%>
    <p>DOST helps you connect with people with similar interests.</p>
  </div>
  <div class="form-box">
  <%= form_with(model: @user, local: true) do |f| %>
      <%= f.text_field :name, class: "form-box-input", placeholder:"Name"%>
      <%= f.email_field :email, class: "form-box-input", placeholder:"Email"%>
      <%= f.password_field :password, class: "form-box-input", placeholder:"Password"%>
     <button onclick= "<%=f.submit %>Signup</button>
    <% end %>
    <hr>
    <div class="create-btn">
    <%=link_to 'Login', login_path,class:"nav-link" %>
    </div>
  </div>
</div>